// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmeVG30IXIf57j2yjMME1Gsxsf3VwzpRg',
    appId: '1:839724178091:web:67ffbb9b19e9874bf1b5ee',
    messagingSenderId: '839724178091',
    projectId: 'chat-app-1c6af',
    authDomain: 'chat-app-1c6af.firebaseapp.com',
    storageBucket: 'chat-app-1c6af.appspot.com',
    measurementId: 'G-P7RSFMCQS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOK2MhXRuUpjDBsqGzWvz_YHSeIiVr7Kw',
    appId: '1:839724178091:android:ce7ef19d72357853f1b5ee',
    messagingSenderId: '839724178091',
    projectId: 'chat-app-1c6af',
    storageBucket: 'chat-app-1c6af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFOLrQ561_zSMfQuC6yKEVPVzVSyVJ7xs',
    appId: '1:839724178091:ios:07c937cd2e2f8568f1b5ee',
    messagingSenderId: '839724178091',
    projectId: 'chat-app-1c6af',
    storageBucket: 'chat-app-1c6af.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFOLrQ561_zSMfQuC6yKEVPVzVSyVJ7xs',
    appId: '1:839724178091:ios:15a9052f8c071198f1b5ee',
    messagingSenderId: '839724178091',
    projectId: 'chat-app-1c6af',
    storageBucket: 'chat-app-1c6af.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
